language: node_js
node_js:
- '6'
- 6.2.2
- '4'
- 4.4.7
notifications:
  email:
    on_success: change
    on_failure: always
cache:
  directories:
  - node_modules
before_install:
- npm install -g npm@3.9.5
after_script:
- npm run coverage
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
- "./node_modules/.bin/codeclimate-test-reporter < ./coverage/lcov.info"
- snyk auth $SNYK_TOKEN && snyk monitor
env:
  global:
  - secure: P66dezg4lLk9r/k5tcW0m5KtZOSYdKGB7ABTKmtMJ5RPdTT1XhMRmR/JgPLRVf4tE6zFDTOkXoEF6oREhhduh1XWJqXma29F22iuNGfDViJZ5pdDu+neHv6bAulcko1QkzPtNrHzPtcY6m3nKL3ILEeIYe7C/vQ+goI7DAsyALqsXE8nQrZ0caq+JL/tA5mXsGbuaTwQrSIz+FaNDzDNmwZXECOxLAmvoO70Vv+52yA7dVhymMB7gwJ7e5YQ2zxkpEEmf9snrjImvHZgCaf/JyGqLQeuZqcWchuW5l3l9+6RS9Olh6zbaI62M9TJnRsaAtbIC6miWxNJg86w2QAUBFmMbu4QOyOTy4oeOkS7M6OvzPQ42moJysTPdDyfPXLG0hK2YA4u8UxJs8V87VVx+/XlMGedAXrs/zJ+aipcaa55ClXVNExZ7bydpr/KEass2N6f/WdTpadY7TXbSksSvbP9LajxD0umnk5NQKzpijGZhDdIsoILQcPR92CMk1tmNFp5HhPSZFhQlFW5mqszfbXSmLlpgYRUo0aVcFA9uLVfm50t9EtZE/J+SG1fwkYKabhrtYwhjA7C0SGTIr0jO7bVoo60B0TXQ84BZwTy45SEPKSWv+pJUsXP8e9CYwprF9W5hvu8PoB/1/JOoGebdzVxLXAsPV4oCDTalWWb+d0=
  - secure: JHcUh1GhufjXgfaC5aepYKorVTiLQo0DH4cdZwIeYMawAY6Mq+EbaSyDG2Wxo+eDlKnmErrh43o1uiLvBFiPNBX0SHSgc8NUuKNnOeRhlpcK+lqRcv8EKbCLJcwH68fvLU+VrNJxJq0smd0NnreKzW7xIzJIQ0+QSLbldgpEXDLtBh3YjH8a88P3IQ6c8ObIYKpcEMna53wyXCl90kRGd5EXy6euAYdK94g8IafRs1u31bhK6BgqfvdLY7lMKcRE24vrp4k5+zfGFOnjuZMTdI+jyQY77+7cKlPGQpzd8hDZMKuZGq78FcJSF1lwyNHTA4Mde57lsL5uxQ0q1LkeTiddkVe3+uaa7gOoBCamR1b7HUbi+4aRxWsY0CV4BCgbLX6CYz4UY17QTAF8BtOBIROH7/8j0DDLQRdszpAgJFkTUM/7dTDY6a2PXf4lpz1vqTILomQwSm6SX0JaQ40E24Sjl47AtNoHREyRojSH+h0nOeMR9BxaufqjLmK2Odt9eXmBs84+NKAzDkGNP9BmuA53IPtXysV1K7P9076EW1o/UdQwGiwcBY1F94TP0rIiop/Mmi5KCFO8CSz8UnEFAh1d2hOSGdjRdl3rUIBLRqcs3HxgOEdCQ/jlqSr+nE/cBxxAfhkje+f7g1nWDWJ2PvcsjNSk+3g+o17ng8eTicw=
  - secure: BkVwb3PE8FOJzYESpAU2KkiDnEJ96jwP2ztmyLT6gILspSfkVGRHRS47plk68tEPyyTAIyPRNdp9VbLJ0EqIk9g7IDq1A/C87GavuwCFiiIQjOjNOIN4Kp9w3k9ABWJjlXHdAf2cDBiadI6xaj40sU9upQXAlABmbRIf2PCUqUX+2Bm4qYrfDJXcQJj5IZ3rVJS+JsKWvOpkxP8oQ9UxsupjxyrKoojKnQxmkX3LcmKwuIxBcBwkQ28HTNWQyCTwjXGu01WPH1/ifTsUD9QsGhqU1envyaJAa6MWMJj7SyWimKJtO7/yhA/Ed5V0HzyropLfi13QOSiKid6DFX7NPVtUBthKRfbwCNwAY7/ECztn4PEU/uIu1igE5I5pLlrfqbdzR+V7paTCMihOR13ceYOrU4WpRwiC7eVRuhAYDygE1gOHXi7B41wlvf8byfnB8TKMmmisKV+Hahn48utcOwvQQTpsSZ5B8wgCDlYgtUmW1aAeLulf5LsnOdKXKp032kd6uTLjlSNLbbIcl9Pj7lxjOzUkds/5yaEB7Te5HZ/2KGepoVU1O0PPF60I7aihPuEUlDpL/jxsHLt6GsT+DhMPfZxLHkN0CWYiUv8tyiy14cw2WRHnYWjYKAkUiIUVkL9T3bF2SZ/aWFrnP7Wus6bWe7/liDD1NFA50wsCfBI=
