language: node_js
node_js:
- '8'
- '6'
notifications:
  email:
    on_success: change
    on_failure: always
after_script:
- npm run coverage
- npm run codeclimate
env:
  global:
    secure: aIP+kciatIWSRm4/ODQGSDobYJ6b1WeY7x+YA44YPwqN/OS8sYg+UNmsRjbjKJxgDTYOySwO7u3sL5lmIHqlXsqhxLx3K9v3Li+yn1HU8rDGNe40uHF0tHSrd7If/sagoh5sHfzlBHKtzff71zywmlD2ti2ykGo6/9T+oAxmq5iiNE9tZcsOlRMfYpDxdyNbvJA+9WgqclJrJx3iU9hed0zuRennQd07I0J041eb7D1oNtFkOFNBFT64t80jrJdgdfUQvn18Q2MtCvjcpWEqavg/lz1FZ7zmSEmv0pyoGakNDm7YfyFM5ZmGj94nxKjI1AoOByUS6+LS9H8thkOwF0zo8cEmikrM/hg6fN+EEAJYqhwtWU+2hD2ozkJmQxhpmSS69HqY5Ww+GUB/Ok8k1/CqR1AIlMlm9P4GUjGt75NPIaEBP7xWHUeuJu3BAkRLJ+iLUwtPGf2cAcM59gE6Mo5zFkVJi/IJoR+Nb/70WUUY3n6kwv/T3MtMcTLon0bGBFGxEEAkzDveqTZr82anBOM6SejgAjN8V7LIfDNUfiwK9KWei6c4Z5dMX7qIr0MzSwT0tWqILVhBKYSTT8ateBp85RsLIrEIdsrgsQIDU0cAkegtqO4ThFOu2zqWvPRHtXyfdWzuDFz4S7TZIA16PJ0rgTCmdXhzSf+xtarjHnI=
